name: Frontend PR
on:
  pull_request:
    branches:
      - main
    paths:
      - frontend/**
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install node modules
        working-directory: ./frontend
        run: npm install
      - name: Run the Tests
        working-directory: ./frontend
        run: npm run test:ci
